### ISSUE TITLE
Add operator null return 문제

### ISSUE THREAD

**Issue by preventionYun** [Rakjunyang/BeautifulCode#22]
Add operation의 경우 다른 operation과 다르게 null을 리턴하고 있는데, 문제가 없을까요? 

![image](https://user-images.githubusercontent.com/15831887/159237260-e5c191e6-53af-416e-8627-62d0c794bd73.png)

Client code에서 해당 result를 아래 부분에서 사용하고 있는데, 현재는 해당 구문이 try catch로 묶여있어서 종료되지는 않네요. 당장은 괜찮겠지만 나중에 처리하면 좋을 듯 합니다!

![image](https://user-images.githubusercontent.com/15831887/159237662-329c3e94-9691-4794-9e61-44bbb1c9bfd1.png)

**Comment by Rakjunyang** [comment]
확인해주셔서 감사합니다!
빈 ArrayList 로 return 하도록 변경해 두겠습니다~
