### ISSUE TITLE
POptionResultMaker에서 sort가 되지 않은 것으로 보입니다

### ISSUE THREAD

**Issue by sga8** [Rakjunyang/BeautifulCode#23]
Merge된 소스내에서도 sort하는 과정이 보이지 않습니다.
output 데이터를 비교했을 때도, sort 되지 않은 것이 확인됩니다 ! 
확인 부탁드립니다

**real output data**
-----------------------------------------
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
-----------------------------------------

**output data**
-----------------------------------------
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,19129568,SRERLALH HMEF,CL2,010-3091-9521,19640910,PRO
SCH,17111236,VSID TVO,CL1,010-3669-1077,20120718,PRO
SCH,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
SCH,17112609,FB NTAWR,CL4,010-5645-6122,20050520,PRO
---------------------------------------

**Comment by preventionYun** [comment]
#25 에서 compare 함수 return 값 수정으로 해결되었습니다. 

https://wjheo.tistory.com/entry/Java-%EC%A0%95%EB%A0%AC%EB%B0%A9%EB%B2%95-Collectionssort

핵심부분은 아래와 같습니다. 
compare( T o1, T o2) 일때 ,
o1 > o2 이면 1
o1 < o2 이면 -1
o1 = o2 이면 0
